export type PoetProfile = {
  id: string;
  name: string;
  century: number;
  years: string;
  place: string;
  genre: string;
  works: string;
  verseCount?: number;
  summary: string;
  sourceUrl: string;
};

export type LibrarySource = {
  id: number;
  title: string;
  author: string;
  period: string;
  type: "پیکرهٔ متن" | "دانش‌نامه" | "دادهٔ پژوهشی" | "زیرساخت داده" | "مجموعهٔ شاعر";
  format: string;
  access: string;
  coverage: string;
  description: string;
  url: string;
  color: "cyan" | "gold" | "wine";
};

export type WorkRecord = {
  id: number;
  title: string;
  author: string;
  century: number;
  form: string;
  kind: "دیوان" | "مثنوی" | "نثر" | "تذکره" | "رباعیات" | "مجموعه";
  url: string;
};

export type LiteraryMovement = {
  title: string;
  centuries: string;
  description: string;
  features: string[];
  figures: string[];
  sourceUrl: string;
};

export const featuredPoets: PoetProfile[] = [
  {
    id: "rudaki",
    name: "رودکی سمرقندی",
    century: 4,
    years: "حدود ۲۴۴–۳۲۹ هـ.ق.",
    place: "پنجکنت، سمرقند",
    genre: "قصیده، قطعه، مثنوی",
    works: "اشعار پراکنده و بازمانده‌های کلیله و دمنه",
    verseCount: 1049,
    summary: "از نخستین چهره‌های بزرگ شعر فارسی دری و شاعر دربار سامانی؛ بخش اندکی از سروده‌های منسوب به او باقی مانده است.",
    sourceUrl: "https://ganjoor.net/roodaki",
  },
  {
    id: "ferdowsi",
    name: "فردوسی توسی",
    century: 4,
    years: "۳۲۹ تا پیش از ۴۱۱ هـ.ق.",
    place: "توس، خراسان",
    genre: "حماسه، مثنوی",
    works: "شاهنامه",
    verseCount: 49656,
    summary: "سرایندهٔ شاهنامه و مهم‌ترین چهرهٔ حماسه‌سرایی فارسی؛ روایت او یکی از پایه‌های حافظهٔ تاریخی و اسطوره‌ای ایران است.",
    sourceUrl: "https://ganjoor.net/ferdousi",
  },
  {
    id: "khayyam",
    name: "خیام نیشابوری",
    century: 5,
    years: "۴۳۹–۵۲۶ هـ.ق.",
    place: "نیشابور",
    genre: "رباعی",
    works: "رباعیات، نوروزنامه",
    verseCount: 780,
    summary: "ریاضی‌دان، منجم و رباعی‌سرای نامدار نیشابور؛ انتساب بسیاری از رباعیات مشهور به او همچنان موضوع پژوهش متن‌شناختی است.",
    sourceUrl: "https://ganjoor.net/khayyam",
  },
  {
    id: "naserkhosrow",
    name: "ناصرخسرو قبادیانی",
    century: 5,
    years: "۳۹۴–حدود ۴۸۱ هـ.ق.",
    place: "قبادیان، بلخ، یمگان",
    genre: "قصیده، سفرنامه، حکمت",
    works: "دیوان، سفرنامه، روشنایی‌نامه، سعادت‌نامه",
    summary: "شاعر، متفکر و سفرنامه‌نویس سدهٔ پنجم که شعر تعلیمی و اندیشهٔ فلسفی و دینی را در زبانی استوار درآمیخت.",
    sourceUrl: "https://ganjoor.net/naserkhosro",
  },
  {
    id: "sanai",
    name: "سنایی غزنوی",
    century: 6,
    years: "سدهٔ ششم هجری",
    place: "غزنه، خراسان",
    genre: "قصیده، غزل، مثنوی عرفانی",
    works: "حدیقةالحقیقه، سیرالعباد، دیوان",
    summary: "از پیشگامان شعر عرفانی فارسی که زبان قصیده و مثنوی را به بستری برای تعلیم اخلاقی و تجربهٔ صوفیانه تبدیل کرد.",
    sourceUrl: "https://ganjoor.net/sanaee",
  },
  {
    id: "nezami",
    name: "نظامی گنجوی",
    century: 6,
    years: "حدود ۵۳۰–۶۰۲ هـ.ق.",
    place: "گنجه",
    genre: "مثنوی روایی، غنایی و حکمی",
    works: "خمسه: مخزن‌الاسرار، خسرو و شیرین، لیلی و مجنون، هفت‌پیکر، اسکندرنامه",
    verseCount: 27772,
    summary: "بزرگ‌ترین منظومه‌پرداز روایی فارسی؛ خمسهٔ او الگویی پایدار برای ادبیات فارسی و سنت‌های ادبی پیرامون آن شد.",
    sourceUrl: "https://ganjoor.net/nezami",
  },
  {
    id: "attar",
    name: "عطار نیشابوری",
    century: 6,
    years: "حدود ۵۴۰–۶۱۸ هـ.ق.",
    place: "نیشابور",
    genre: "مثنوی عرفانی، غزل، تذکره",
    works: "منطق‌الطیر، الهی‌نامه، مصیبت‌نامه، تذکرةالاولیا",
    verseCount: 94999,
    summary: "شاعر و نویسندهٔ صوفی نیشابور؛ روایت تمثیلی، حکایت و غزل را برای صورت‌بندی تجربهٔ عرفانی به کار گرفت.",
    sourceUrl: "https://ganjoor.net/attar",
  },
  {
    id: "rumi",
    name: "مولانا جلال‌الدین بلخی",
    century: 7,
    years: "۶۰۴–۶۷۲ هـ.ق.",
    place: "بلخ، قونیه",
    genre: "غزل، مثنوی عرفانی، نثر تعلیمی",
    works: "مثنوی معنوی، دیوان شمس، فیه ما فیه",
    verseCount: 65746,
    summary: "شاعر و عارف فارسی‌زبان که مثنوی و غزل را به اوج تازه‌ای رساند؛ زندگی و آثارش شبکه‌ای فرامنطقه‌ای از بلخ تا آناتولی ساخته‌اند.",
    sourceUrl: "https://ganjoor.net/moulavi",
  },
  {
    id: "saadi",
    name: "سعدی شیرازی",
    century: 7,
    years: "حدود ۶۰۰–۶۹۴ هـ.ق.",
    place: "شیراز",
    genre: "غزل، قصیده، حکایت، نثر مسجع",
    works: "بوستان، گلستان، غزلیات و قصاید",
    verseCount: 16120,
    summary: "شاعر و نویسندهٔ شیرازی؛ بوستان و گلستان را در میانهٔ سدهٔ هفتم پدید آورد و بر زبان و اخلاق ادبی فارسی اثری دیرپا گذاشت.",
    sourceUrl: "https://ganjoor.net/saadi",
  },
  {
    id: "khajoo",
    name: "خواجوی کرمانی",
    century: 8,
    years: "۶۸۹–۷۵۳ هـ.ق.",
    place: "کرمان، شیراز، تبریز",
    genre: "غزل، قصیده، مثنوی",
    works: "دیوان، همای و همایون، گل و نوروز، روضةالانوار",
    verseCount: 29301,
    summary: "شاعر پرکار سدهٔ هشتم و حلقه‌ای مهم میان سنت نظامی، غزل عراقی و فضای ادبی شیراز پیش از حافظ.",
    sourceUrl: "https://ganjoor.net/khajoo",
  },
  {
    id: "jahan",
    name: "جهان‌ملک خاتون",
    century: 8,
    years: "پیش از ۷۲۴ تا حدود ۷۸۴–۷۹۵ هـ.ق.",
    place: "شیراز",
    genre: "غزل، قصیده، قطعه، رباعی",
    works: "دیوان جهان‌ملک خاتون",
    summary: "شاعر اینجوی شیراز و هم‌دورهٔ حافظ و عبید زاکانی؛ دیوان پرحجم او یکی از مهم‌ترین مجموعه‌های به‌جامانده از زنان شاعر پیشامدرن است.",
    sourceUrl: "https://ganjoor.net/jahan",
  },
  {
    id: "obeyd",
    name: "عبید زاکانی",
    century: 8,
    years: "سدهٔ هشتم هجری",
    place: "قزوین، شیراز",
    genre: "طنز، هزل، غزل، رساله",
    works: "اخلاق‌الاشراف، موش و گربه، رسالهٔ دلگشا، کلیات",
    summary: "طنزپرداز و شاعر برجستهٔ سدهٔ هشتم که نقد اجتماعی و سیاسی را در قالب رساله، حکایت، هزل و شعر دنبال کرد.",
    sourceUrl: "https://ganjoor.net/obeyd",
  },
  {
    id: "hafez",
    name: "حافظ شیرازی",
    century: 8,
    years: "حدود ۷۲۶–۷۹۲ هـ.ق.",
    place: "شیراز",
    genre: "غزل، قصیده، قطعه، رباعی",
    works: "دیوان حافظ",
    verseCount: 5284,
    summary: "غزل‌سرای بزرگ سدهٔ هشتم؛ شعر او با ایهام، موسیقی، چندصدایی و گفت‌وگوی پیچیده با سنت عرفانی و درباری شناخته می‌شود.",
    sourceUrl: "https://ganjoor.net/hafez",
  },
  {
    id: "jami",
    name: "عبدالرحمن جامی",
    century: 9,
    years: "۸۱۷–۸۹۸ هـ.ق.",
    place: "جام، هرات",
    genre: "غزل، مثنوی، شرح عرفانی، تذکره",
    works: "هفت اورنگ، بهارستان، نفحات‌الانس، سه دیوان",
    verseCount: 39776,
    summary: "شاعر، عارف و دانشمند نامدار هرات؛ بیش از چهل اثر به او نسبت داده شده و هفت اورنگ مهم‌ترین مجموعهٔ مثنوی‌های اوست.",
    sourceUrl: "https://ganjoor.net/jami",
  },
  {
    id: "ahli",
    name: "اهلی شیرازی",
    century: 10,
    years: "۸۵۸–۹۴۲ هـ.ق.",
    place: "شیراز",
    genre: "غزل، قصیده، مثنوی",
    works: "دیوان، سحر حلال، شمع و پروانه",
    summary: "شاعر شیرازی آغاز دورهٔ صفوی که صنایع ادبی و تجربه‌های فرمی در غزل و مثنوی از ویژگی‌های شناخته‌شدهٔ آثار اوست.",
    sourceUrl: "https://ganjoor.net/ahli",
  },
  {
    id: "saeb",
    name: "صائب تبریزی",
    century: 11,
    years: "حدود ۱۰۰۰–۱۰۸۷ هـ.ق.",
    place: "تبریز، اصفهان، هند",
    genre: "غزل، قصیده",
    works: "دیوان صائب",
    summary: "از شاخص‌ترین غزل‌سرایان سبک هندی؛ تصویرسازی فشرده، مضمون‌آفرینی و پیوند تجربهٔ روزمره با نکته‌های حکمی در شعر او برجسته است.",
    sourceUrl: "https://ganjoor.net/saeb",
  },
  {
    id: "bidel",
    name: "بیدل دهلوی",
    century: 11,
    years: "۱۰۵۴–۱۱۳۳ هـ.ق.",
    place: "هند، دهلی",
    genre: "غزل، مثنوی، رباعی، نثر",
    works: "کلیات بیدل، چهار عنصر، عرفان، طور معرفت",
    summary: "شاعر و متفکر فارسی‌زبان هند؛ زبان فشرده، خیال پیچیده و تأمل فلسفی او شاخه‌ای مهم از شعر فارسی در شبه‌قاره را نمایندگی می‌کند.",
    sourceUrl: "https://ganjoor.net/bidel",
  },
  {
    id: "parvin",
    name: "پروین اعتصامی",
    century: 14,
    years: "۱۲۸۵–۱۳۲۰ هـ.ش.",
    place: "تبریز، تهران",
    genre: "قطعه، قصیده، مناظره",
    works: "دیوان پروین اعتصامی",
    verseCount: 5612,
    summary: "شاعر معاصر و از برجسته‌ترین صداهای زن در شعر فارسی؛ مناظره، تمثیل اخلاقی و توجه به عدالت اجتماعی از ویژگی‌های شعر اوست.",
    sourceUrl: "https://ganjoor.net/parvin",
  },
  {
    id: "bahar",
    name: "محمدتقی بهار",
    century: 14,
    years: "۱۲۶۵–۱۳۳۰ هـ.ش.",
    place: "مشهد، تهران",
    genre: "قصیده، شعر سیاسی، پژوهش ادبی",
    works: "دیوان بهار، سبک‌شناسی، تاریخ احزاب سیاسی",
    summary: "ملک‌الشعرای بهار، شاعر، روزنامه‌نگار و پژوهشگر؛ پلی میان سنت قصیده و تجربهٔ سیاسی و فکری ایران معاصر.",
    sourceUrl: "https://ganjoor.net/bahar",
  },
  {
    id: "abusaeed",
    name: "ابوسعید ابوالخیر",
    century: 4,
    years: "۳۵۷–۴۴۰ هـ.ق.",
    place: "میهنه، خراسان",
    genre: "رباعی، گفتار عرفانی",
    works: "رباعیات و سخنان منسوب",
    summary: "عارف نامدار خراسان که رباعیات و حکایات منسوب به او در شکل‌گیری زبان موجز و تجربی عرفان فارسی اثرگذار بوده‌اند.",
    sourceUrl: "https://ganjoor.net/abusaeed",
  },
  {
    id: "onsori",
    name: "عنصری بلخی",
    century: 4,
    years: "درگذشتهٔ حدود ۴۳۱ هـ.ق.",
    place: "بلخ، غزنه",
    genre: "قصیده، مدح، مثنوی",
    works: "دیوان و منظومه‌های بازمانده",
    summary: "از مهم‌ترین قصیده‌سرایان دربار غزنوی و یکی از چهره‌های مرکزی سنت مدحی و توصیفی سبک خراسانی.",
    sourceUrl: "https://ganjoor.net/onsori",
  },
  {
    id: "babataher",
    name: "باباطاهر عریان",
    century: 5,
    years: "سدهٔ پنجم هجری",
    place: "همدان",
    genre: "دوبیتی، کلمات قصار",
    works: "دوبیتی‌ها و کلمات قصار",
    summary: "شاعر و عارف ایرانی که دوبیتی‌های منسوب به او با زبانی نزدیک به گویش‌های ایرانی غربی و مضامین عاشقانه و عرفانی شناخته می‌شوند.",
    sourceUrl: "https://ganjoor.net/babataher",
  },
  {
    id: "khajehabdollah",
    name: "خواجه عبدالله انصاری",
    century: 5,
    years: "۳۹۶–۴۸۱ هـ.ق.",
    place: "هرات",
    genre: "مناجات، نثر عرفانی، طبقات‌نویسی",
    works: "مناجات‌نامه، طبقات‌الصوفیه، رسائل",
    summary: "عارف و نویسندهٔ هروی که نثر آهنگین و مناجات‌های فارسی او در تاریخ نثر عرفانی جایگاهی ممتاز دارند.",
    sourceUrl: "https://ganjoor.net/abdullah",
  },
  {
    id: "asadi",
    name: "اسدی توسی",
    century: 5,
    years: "درگذشتهٔ حدود ۴۶۵ هـ.ق.",
    place: "توس، نخجوان",
    genre: "حماسه، مناظره، فرهنگ‌نویسی",
    works: "گرشاسپ‌نامه، لغت فرس، مناظرات",
    summary: "حماسه‌سرای پس از فردوسی و مؤلف لغت فرس؛ گرشاسپ‌نامهٔ او شاخه‌ای مهم از روایت‌های پهلوانی فارسی را حفظ کرده است.",
    sourceUrl: "https://ganjoor.net/asadi",
  },
  {
    id: "manoochehri",
    name: "منوچهری دامغانی",
    century: 5,
    years: "نیمهٔ نخست سدهٔ پنجم",
    place: "دامغان، غزنه",
    genre: "قصیده، مسمط، وصف طبیعت",
    works: "دیوان منوچهری",
    summary: "قصیده‌سرای دورهٔ غزنوی و از استادان تصویر طبیعت، موسیقی واژه و قالب مسمط؛ آشنایی او با شعر عربی در آثارش آشکار است.",
    sourceUrl: "https://ganjoor.net/manoochehri",
  },
  {
    id: "anvari",
    name: "انوری ابیوردی",
    century: 6,
    years: "درگذشتهٔ حدود ۵۸۳ هـ.ق.",
    place: "ابیورد، بلخ، خراسان",
    genre: "قصیده، غزل، قطعه",
    works: "دیوان انوری",
    summary: "شاعر و دانشمند سدهٔ ششم با آگاهی از منطق، موسیقی، ریاضی و نجوم؛ قصاید مدحی و اجتماعی او دامنهٔ زبانی گسترده‌ای دارند.",
    sourceUrl: "https://ganjoor.net/anvari",
  },
  {
    id: "khaghani",
    name: "خاقانی شروانی",
    century: 6,
    years: "۵۲۰–حدود ۵۸۱/۵۹۵ هـ.ق.",
    place: "شروان، تبریز",
    genre: "قصیده، غزل، سفرنامهٔ منظوم",
    works: "دیوان خاقانی، تحفةالعراقین",
    summary: "از بزرگ‌ترین قصیده‌سرایان فارسی؛ ترکیب‌سازی، دانش گسترده و تصویرهای فشرده، زبان شعر او را پیچیده و متمایز کرده است.",
    sourceUrl: "https://ganjoor.net/khaghani",
  },
  {
    id: "mahsati",
    name: "مهستی گنجوی",
    century: 6,
    years: "درگذشتهٔ حدود ۵۷۶–۵۷۷ هـ.ق.",
    place: "گنجه",
    genre: "رباعی، قطعه، غزل",
    works: "رباعیات و دیوان اشعار",
    verseCount: 800,
    summary: "از زنان شاعر متقدم فارسی و رباعی‌سرایی برجسته؛ گنجور مجموعه‌ای ۸۰۰ بیتی از رباعیات و اشعار منسوب به او دارد.",
    sourceUrl: "https://ganjoor.net/mahsati",
  },
  {
    id: "amirkhosro",
    name: "امیرخسرو دهلوی",
    century: 7,
    years: "۶۵۱/۶۵۲–۷۲۵ هـ.ق.",
    place: "دهلی، هند",
    genre: "غزل، قصیده، مثنوی روایی",
    works: "دیوان‌ها، مطلع‌الانوار، خسرو و شیرین، مجنون و لیلی، هشت بهشت",
    verseCount: 21598,
    summary: "شاعر و عارف بزرگ فارسی‌گوی هند و از مهم‌ترین حلقه‌های انتقال سنت غزل و خمسه‌سرایی به شبه‌قاره.",
    sourceUrl: "https://ganjoor.net/khosro",
  },
  {
    id: "eraghi",
    name: "فخرالدین عراقی",
    century: 7,
    years: "درگذشتهٔ ۶۸۶ یا ۶۸۸ هـ.ق.",
    place: "همدان، هند، قونیه، دمشق",
    genre: "غزل، مثنوی، نثر عرفانی",
    works: "دیوان، عشاق‌نامه، لمعات، رسالهٔ اصطلاحات",
    verseCount: 5965,
    summary: "شاعر و عارف سدهٔ هفتم که میان تصوف خراسان، هند و آناتولی پیوند برقرار کرد؛ لمعات او اثری کلیدی در نثر عرفانی است.",
    sourceUrl: "https://ganjoor.net/eraghi",
  },
  {
    id: "ouhadi",
    name: "اوحدی مراغه‌ای",
    century: 8,
    years: "حدود ۶۷۳–۷۳۸ هـ.ق.",
    place: "مراغه، اصفهان",
    genre: "مثنوی تعلیمی، غزل، قصیده",
    works: "جام جم، منطق‌العشاق، دیوان",
    summary: "شاعر عارف سدهٔ هشتم که مثنوی جام جم را با محور اخلاق، جامعه و سلوک سرود و در غزل نیز پیرو سنت عراقی بود.",
    sourceUrl: "https://ganjoor.net/ouhadi",
  },
  {
    id: "salman",
    name: "سلمان ساوجی",
    century: 8,
    years: "حدود ۷۰۹–۷۷۸ هـ.ق.",
    place: "ساوه، بغداد، تبریز",
    genre: "قصیده، غزل، مثنوی",
    works: "دیوان، جمشید و خورشید، فراق‌نامه",
    summary: "شاعر دربار جلایریان و از استادان قصیده و غزل سدهٔ هشتم؛ صنایع بدیعی و ترکیب سنت مدحی با غزل در آثارش برجسته است.",
    sourceUrl: "https://ganjoor.net/salman",
  },
  {
    id: "seyf",
    name: "سیف فرغانی",
    century: 8,
    years: "درگذشتهٔ ۷۴۹ هـ.ق.",
    place: "فرغانه، آذربایجان، آقسرا",
    genre: "غزل، قصیده، رباعی",
    works: "دیوان سیف فرغانی",
    verseCount: 10279,
    summary: "شاعر صوفی نیمهٔ دوم سدهٔ هفتم و آغاز سدهٔ هشتم؛ دیوان او بیش از ده هزار بیت دارد و ارادتش به سعدی در شعر و مکاتبات بازتاب یافته است.",
    sourceUrl: "https://ganjoor.net/seyf",
  },
  {
    id: "shahnematollah",
    name: "شاه نعمت‌الله ولی",
    century: 8,
    years: "۷۳۱–۸۳۴ هـ.ق.",
    place: "حلب، سمرقند، کرمان، ماهان",
    genre: "غزل، قصیده، رسالهٔ عرفانی",
    works: "دیوان و رسائل عرفانی",
    summary: "عارف و شاعر و بنیان‌گذار طریقت نعمت‌اللهی؛ سفرهای گسترده و اقامت او در ماهان شبکه‌ای فرامنطقه‌ای از تصوف فارسی پدید آورد.",
    sourceUrl: "https://ganjoor.net/shahnematollah",
  },
  {
    id: "shabestari",
    name: "شیخ محمود شبستری",
    century: 8,
    years: "درگذشتهٔ حدود ۷۲۰ هـ.ق.",
    place: "شبستر، تبریز",
    genre: "مثنوی عرفانی، رساله",
    works: "گلشن راز، سعادت‌نامه، حق‌الیقین",
    summary: "عارف و شاعر آذربایجانی که گلشن راز را در پاسخ به پرسش‌های عرفانی سرود؛ این اثر از متون فشرده و پرشرح تصوف فارسی است.",
    sourceUrl: "https://ganjoor.net/shabestari",
  },
  {
    id: "khojandi",
    name: "کمال خجندی",
    century: 8,
    years: "درگذشتهٔ حدود ۸۰۳ هـ.ق.",
    place: "خجند، تبریز",
    genre: "غزل، قصیده",
    works: "دیوان کمال خجندی",
    summary: "غزل‌سرای سدهٔ هشتم که بخش مهمی از زندگی خود را در تبریز گذراند؛ زبان عاشقانه و موسیقی غزل او شهرت دارد.",
    sourceUrl: "https://ganjoor.net/khojandi",
  },
  {
    id: "bahaee",
    name: "شیخ بهایی",
    century: 10,
    years: "۹۵۳–۱۰۳۰ هـ.ق.",
    place: "بعلبک، قزوین، اصفهان",
    genre: "غزل، رباعی، مثنوی، نثر علمی",
    works: "کشکول، نان و حلوا، شیر و شکر، دیوان",
    verseCount: 465,
    summary: "دانشمند و نویسندهٔ دورهٔ صفوی با ده‌ها کتاب و رساله در ادب، فقه، ریاضی و نجوم؛ شعر فارسی او قالب‌های متنوعی دارد.",
    sourceUrl: "https://ganjoor.net/bahaee",
  },
  {
    id: "vahshi",
    name: "وحشی بافقی",
    century: 10,
    years: "درگذشتهٔ حدود ۹۹۹ هـ.ق.",
    place: "بافق، یزد، کاشان",
    genre: "غزل، مثنوی، ترکیب‌بند",
    works: "دیوان، ناظر و منظور، فرهاد و شیرین، خلد برین",
    verseCount: 5824,
    summary: "غزل‌سرای نامدار سدهٔ دهم؛ زبان عاطفی و روان و منظومه‌های روایی او جایگاهی مهم در ادامهٔ سنت غزل و مثنوی دارند.",
    sourceUrl: "https://ganjoor.net/vahshi",
  },
  {
    id: "mohtasham",
    name: "محتشم کاشانی",
    century: 10,
    years: "۹۰۵–۹۹۶ هـ.ق.",
    place: "کاشان",
    genre: "غزل، قصیده، ترکیب‌بند، مرثیه",
    works: "دیوان، دوازده‌بند، جلالیه",
    verseCount: 10716,
    summary: "شاعر دورهٔ صفوی و سرایندهٔ دوازده‌بند مشهور؛ دیوان او افزون بر مرثیه، غزل، قصیده، قطعه و مثنوی را نیز دربرمی‌گیرد.",
    sourceUrl: "https://ganjoor.net/mohtasham",
  },
  {
    id: "kalim",
    name: "کلیم کاشانی",
    century: 11,
    years: "۹۹۰–۱۰۶۱ هـ.ق.",
    place: "همدان، کاشان، کشمیر",
    genre: "غزل، قصیده، مثنوی",
    works: "دیوان کلیم، پادشاه‌نامه",
    summary: "از چهره‌های برجستهٔ سبک هندی؛ از ایران به هند رفت و در کشمیر درگذشت. مضمون‌آفرینی و مشاهدهٔ جزئیات روزمره در غزل او برجسته است.",
    sourceUrl: "https://ganjoor.net/kalim",
  },
  {
    id: "hatef",
    name: "هاتف اصفهانی",
    century: 12,
    years: "سدهٔ دوازدهم هجری",
    place: "اصفهان، قم",
    genre: "غزل، قصیده، ترجیع‌بند، رباعی",
    works: "دیوان و ترجیع‌بند توحیدی",
    verseCount: 1490,
    summary: "شاعر دورهٔ افشاریه و زندیه و از حلقهٔ مشتاق اصفهانی؛ ترجیع‌بند توحیدی او از مشهورترین نمونه‌های این قالب است.",
    sourceUrl: "https://ganjoor.net/hatef",
  },
  {
    id: "forooghi",
    name: "فروغی بسطامی",
    century: 13,
    years: "۱۲۱۳–۱۲۷۴ هـ.ق.",
    place: "کربلا، مازندران، تهران",
    genre: "غزل",
    works: "دیوان فروغی بسطامی",
    summary: "غزل‌سرای دورهٔ قاجار و از نمایندگان بازگشت ادبی؛ در غزل شیوهٔ سعدی را دنبال کرد و با قاآنی معاشر بود.",
    sourceUrl: "https://ganjoor.net/forooghi",
  },
  {
    id: "ghaani",
    name: "قاآنی شیرازی",
    century: 13,
    years: "۱۲۲۳–۱۲۷۰ هـ.ق.",
    place: "شیراز، مشهد، تهران",
    genre: "قصیده، غزل، قطعه، نثر",
    works: "دیوان قاآنی، پریشان",
    summary: "شاعر نامدار عهد قاجار با مهارت در ادبیات فارسی و عربی؛ قصاید او ادامهٔ آگاهانهٔ سنت خراسانی در دورهٔ بازگشت‌اند.",
    sourceUrl: "https://ganjoor.net/ghaani",
  },
  {
    id: "farrokhi",
    name: "فرخی سیستانی",
    century: 5,
    years: "درگذشتهٔ ۴۲۹ هـ.ق.",
    place: "سیستان، غزنه",
    genre: "قصیده، غزل، موسیقی",
    works: "دیوان فرخی سیستانی",
    summary: "قصیده‌سرای بزرگ دورهٔ غزنوی و نوازنده‌ای آشنا با موسیقی؛ وصف طبیعت، جشن‌ها، سفر و زندگی درباری در شعر روان و تصویری او جایگاهی برجسته دارد.",
    sourceUrl: "https://ganjoor.net/farrokhi",
  },
  {
    id: "ghatran",
    name: "قطران تبریزی",
    century: 5,
    years: "درگذشتهٔ حدود ۴۶۵ هـ.ق.",
    place: "تبریز، آذربایجان",
    genre: "قصیده، مدح، حکمت",
    works: "دیوان قطران تبریزی",
    verseCount: 9441,
    summary: "از نخستین شاعران بزرگ فارسی‌گوی آذربایجان و قصیده‌سرایی اثرگذار در سدهٔ پنجم؛ دیوان او منبعی مهم برای تاریخ سیاسی و فرهنگی قفقاز و آذربایجان است.",
    sourceUrl: "https://ganjoor.net/ghatran",
  },
  {
    id: "masood",
    name: "مسعود سعد سلمان",
    century: 5,
    years: "حدود ۴۳۸–۵۱۵ هـ.ق.",
    place: "لاهور، غزنه",
    genre: "قصیده، حبسیه، قطعه",
    works: "دیوان مسعود سعد سلمان و حبسیات",
    verseCount: 15062,
    summary: "شاعر ایرانی‌تبار لاهور و از نامدارترین سرایندگان حبسیه؛ تجربهٔ سال‌های زندان را با قصیده‌پردازی فنی و بیانی شخصی درآمیخت.",
    sourceUrl: "https://ganjoor.net/masood",
  },
  {
    id: "eynolghozat",
    name: "عین‌القضات همدانی",
    century: 6,
    years: "۴۹۲–۵۲۵ هـ.ق.",
    place: "همدان، خراسان",
    genre: "نثر عرفانی، رباعی، حکمت",
    works: "تمهیدات، لوایح، نامه‌ها",
    summary: "متفکر، نویسنده و عارف سدهٔ ششم که نثر شورمند فارسی را با تأمل فلسفی و تجربهٔ عرفانی پیوند زد؛ نامه‌های او نیز سندی مهم از نثر شخصی آن دوره‌اند.",
    sourceUrl: "https://ganjoor.net/eynolghozat",
  },
  {
    id: "babaafzal",
    name: "باباافضل کاشانی",
    century: 6,
    years: "سدهٔ ششم تا حدود ۶۱۰ هـ.ق.",
    place: "کاشان",
    genre: "رباعی، نثر فلسفی، حکمت",
    works: "رباعیات و رساله‌های حکمی",
    summary: "فیلسوف و نویسندهٔ فارسی‌نویس کاشانی؛ رباعیات فراوانی به او نسبت داده شده و رساله‌هایش از نمونه‌های مهم بیان فلسفی به زبان فارسی‌اند.",
    sourceUrl: "https://ganjoor.net/babaafzal",
  },
  {
    id: "homam",
    name: "همام تبریزی",
    century: 7,
    years: "۶۳۶–۷۱۴ هـ.ق.",
    place: "تبریز",
    genre: "غزل، قصیده، مثنوی",
    works: "دیوان همام تبریزی",
    summary: "غزل‌سرای برجستهٔ تبریز و هم‌روزگار سعدی؛ شعر او حلقه‌ای مهم در گسترش غزل عراقی در آذربایجان و محافل ادبی ایلخانی است.",
    sourceUrl: "https://ganjoor.net/homam",
  },
  {
    id: "ebneyamin",
    name: "ابن یمین فریومدی",
    century: 8,
    years: "۶۸۵–۷۶۹ هـ.ق.",
    place: "فریومد، سبزوار",
    genre: "قطعه، قصیده، غزل",
    works: "دیوان ابن یمین",
    summary: "شاعر خراسانی و استاد قطعه‌سرایی؛ اندرز، اخلاق، کار، دانش و تجربهٔ اجتماعی در قطعات موجز و روشن او بازتاب گسترده‌ای یافته‌اند.",
    sourceUrl: "https://ganjoor.net/ebneyamin",
  },
  {
    id: "ghasem",
    name: "قاسم انوار",
    century: 8,
    years: "۷۵۷–۸۳۷ هـ.ق.",
    place: "سراب، هرات، تربت جام",
    genre: "غزل عرفانی، مثنوی، قطعه",
    works: "دیوان قاسم انوار",
    summary: "شاعر و عارف دورهٔ تیموری که میان آذربایجان، خراسان و هرات رفت‌وآمد داشت؛ شعر او شبکهٔ خانقاهی و زبان غزل عرفانی آن عصر را بازتاب می‌دهد.",
    sourceUrl: "https://ganjoor.net/ghasem",
  },
  {
    id: "orfi",
    name: "عرفی شیرازی",
    century: 10,
    years: "۹۶۳–۹۹۹ هـ.ق.",
    place: "شیراز، لاهور",
    genre: "قصیده، غزل، سبک هندی",
    works: "دیوان عرفی شیرازی",
    summary: "شاعر مهاجر شیرازی در هند و از چهره‌های اثرگذار گذار به سبک هندی؛ زبان فشرده و مضمون‌های تازهٔ او در ایران و شبه‌قاره پیروان بسیار یافت.",
    sourceUrl: "https://ganjoor.net/orfi",
  },
  {
    id: "naziri",
    name: "نظیری نیشابوری",
    century: 10,
    years: "نیمهٔ دوم سدهٔ دهم–۱۰۲۱ هـ.ق.",
    place: "نیشابور، آگره",
    genre: "غزل، قصیده، سبک هندی",
    works: "دیوان نظیری نیشابوری",
    summary: "شاعر نیشابوری مهاجر به هند و از صداهای اثرگذار شعر فارسی در دربار گورکانی؛ غزل‌هایش در شکل‌گیری زبان تصویری سبک هندی اهمیت دارند.",
    sourceUrl: "https://ganjoor.net/naziri",
  },
  {
    id: "feyz",
    name: "فیض کاشانی",
    century: 11,
    years: "۱۰۰۷–۱۰۹۰ هـ.ق.",
    place: "کاشان، شیراز، قم",
    genre: "غزل، قصیده، شعر عرفانی",
    works: "دیوان فیض و رساله‌های عرفانی و حکمی",
    summary: "دانشمند، فیلسوف، محدث و شاعر دورهٔ صفوی؛ شعر عرفانی او بخشی از کارنامه‌ای بسیار گسترده در حکمت، اخلاق و علوم دینی است.",
    sourceUrl: "https://ganjoor.net/feyz",
  },
  {
    id: "hazin",
    name: "حزین لاهیجی",
    century: 12,
    years: "زادهٔ ۱۱۰۳ هـ.ق.؛ فعال در سدهٔ دوازدهم",
    place: "اصفهان، لاهیجان، بنارس",
    genre: "غزل، قصیده، تذکره و خاطرات",
    works: "دیوان حزین، تذکرةالمعاصرین",
    summary: "شاعر و دانشمند اواخر صفوی که پس از آشوب‌های ایران به هند مهاجرت کرد؛ آثارش پیوند ادبی ایران و شبه‌قاره و تجربهٔ مهاجرت را مستند می‌کنند.",
    sourceUrl: "https://ganjoor.net/hazin",
  },
  {
    id: "azar",
    name: "آذر بیگدلی",
    century: 12,
    years: "۱۱۳۴–۱۱۹۵ هـ.ق.",
    place: "اصفهان، قم",
    genre: "غزل، قصیده، تذکره‌نویسی",
    works: "آتشکدهٔ آذر، دیوان اشعار",
    summary: "شاعر و تذکره‌نویس دورهٔ زندیه؛ آتشکدهٔ آذر را طی چند دهه گرد آورد و مجموعه‌ای پرارج از زندگی‌نامه و نمونهٔ شعر شاعران فارسی‌گو پدید آورد.",
    sourceUrl: "https://ganjoor.net/azar",
  },
];

const directoryByCentury: Record<number, string[]> = {
  3: ["ابوحفص سغدی", "ابوسلیک گرگانی", "بسام کرد", "حنظلهٔ بادغیسی", "رودکی", "فیروز مشرقی", "محمد بن مخلد سگزی", "محمد وصیف سگزی", "محمود وراق هروی"],
  4: ["ابواسحاق جویباری", "ابوالحسین خارجی", "ابوالعلاء شوشتری", "ابوالمؤید بلخی", "ابوالمثل بخارایی", "ابوسعید ابوالخیر", "ابوطیب مصعبی", "احمد برمکی", "بلعمی", "ترکی کشی", "جلاب بخارایی", "دقیقی", "رونقی بخارایی", "سپهری بخارایی", "شاکر بخارایی", "شهید بلخی", "صانع بلخی", "طخاری", "عنصری", "عیوقی", "فرالاوی", "فردوسی", "کسایی", "مرادی", "مسعودی مروزی"],
  5: ["ابوالفرج رونی", "ابوالفضل بیهقی", "ابوعلی عثمانی", "ازرقی هروی", "اسدی توسی", "امیر معزی", "ایرانشان", "باباطاهر", "خواجه عبدالله انصاری", "خیام", "سرایندهٔ فرامرزنامه", "سنایی", "عسجدی", "عمعق بخاری", "عنصرالمعالی", "غزالی", "فخرالدین اسعد گرگانی", "فرخی سیستانی", "قطران تبریزی", "لبیبی", "مسعود سعد سلمان", "منوچهری", "ناصرخسرو", "هجویری"],
  6: ["اثیر اخسیکتی", "ادیب صابر", "انوری", "اوحدالدین کرمانی", "باباافضل کاشانی", "بهاء ولد", "جمال‌الدین عبدالرزاق", "حمیدالدین بلخی", "خاقانی", "سراج قمری", "سوزنی سمرقندی", "سید حسن غزنوی", "ظهیر فاریابی", "ظهیری سمرقندی", "عبادی مروزی", "عبدالقادر گیلانی", "عبدالواسع جبلی", "عثمان مختاری", "عطار", "عین‌القضات همدانی", "فلکی شروانی", "قوامی رازی", "مجیرالدین بیلقانی", "محمد بن منور", "مهستی گنجوی", "میبدی", "نصرالله منشی", "نظامی", "نظامی عروضی", "وطواط"],
  7: ["امامی هروی", "امیر حسینی هروی", "امیرخسرو دهلوی", "حکیم نزاری", "خواجه نصیرالدین طوسی", "سعدالدین وراوینی", "سعدی", "سلطان ولد", "عراقی", "کمال‌الدین اسماعیل", "مجد همگر", "مولانا", "نجم‌الدین رازی", "همام تبریزی"],
  8: ["ابن عماد", "ابن یمین", "اوحدی مراغه‌ای", "جلال عضد", "جنید شیرازی", "جهان ملک خاتون", "حافظ", "حیدر شیرازی", "خواجوی کرمانی", "سلمان ساوجی", "سیف فرغانی", "شاه نعمت‌الله ولی", "شمس مغربی", "شیخ محمود شبستری", "عبید زاکانی", "قاسم انوار", "کمال خجندی", "محمد کوسج", "ناصر بخارایی", "نسیمی"],
  9: ["ابن حسام خوسفی", "اسیری لاهیجی", "امیر شاهی", "امیرعلیشیر نوایی", "جامی", "حسین خوارزمی", "خیالی بخارایی", "سلیمی جرونی", "صوفی محمد هروی", "کوهی", "نظام قاری"],
  10: ["اهلی شیرازی", "بابافغانی", "رضی‌الدین آرتیمانی", "سام میرزا صفوی", "شاهدی", "شیخ بهایی", "عرفی", "فضولی", "محتشم کاشانی", "میلی", "نظیری نیشابوری", "وحشی بافقی", "هلالی جغتایی"],
  11: ["ابوالحسن فراهانی", "اسیر شهرستانی", "امیر پازواری", "بیدل دهلوی", "جویای تبریزی", "سلطان باهو", "سلیم تهرانی", "سیدای نسفی", "صائب", "طغرای مشهدی", "غنی کشمیری", "فصیحی هروی", "فیاض لاهیجی", "فیض کاشانی", "قدسی مشهدی", "کلیم", "مجذوب تبریزی", "ملا مسیح", "میرداماد", "نورس دماوندی", "نوعی خبوشانی", "واعظ قزوینی", "وحیدالزمان قزوینی"],
  12: ["آذر بیگدلی", "حزین لاهیجی", "رفیق اصفهانی", "سعیدا", "طبیب اصفهانی", "قصاب کاشانی", "مشتاق اصفهانی", "نورعلیشاه", "هاتف اصفهانی"],
  13: ["آشفتهٔ شیرازی", "اشراق بیرجندی", "افسر کرمانی", "الهامی کرمانشاهی", "بلند اقبال", "ترکی شیرازی", "جیحون یزدی", "حکیم سبزواری", "خالد نقشبندی", "رشحه", "رضاقلی خان هدایت", "ساغر کنگاوری", "سحاب اصفهانی", "شاطر عباس صبوحی", "صامت بروجردی", "صفای اصفهانی", "صفایی جندقی", "صفی علیشاه", "عمان سامانی", "غالب دهلوی", "غبار همدانی", "فایز", "فروغی بسطامی", "قاآنی", "قائم مقام فراهانی", "محیط قمی", "ملا احمد نراقی", "میرزا آقاخان کرمانی", "میرزا حبیب خراسانی", "نشاط اصفهانی", "نیر تبریزی", "وحدت کرمانشاهی", "وفایی شوشتری", "وفایی مهابادی", "یغمای جندقی"],
  14: ["آیتی بیرجندی", "ادیب الممالک", "افسرالملوک عاملی", "اقبال لاهوری", "ایرج میرزا", "پروین اعتصامی", "حاجب شیرازی", "خلیل‌الله خلیلی", "رهی معیری", "شهریار", "صابر همدانی", "صغیر اصفهانی", "طغرل احراری", "عارف قزوینی", "عبدالرحیم حائری", "غروی اصفهانی", "فرخی یزدی", "فنودی", "ملک‌الشعرا بهار", "میرزاده عشقی"],
};

export const poetDirectory = Object.entries(directoryByCentury).flatMap(([century, names]) =>
  names.map(name => ({ name, century: Number(century) })),
);

const workSeed: Omit<WorkRecord, "id">[] = [
  { title: "اشعار بازمانده", author: "رودکی", century: 4, form: "قصیده، قطعه و ابیات پراکنده", kind: "مجموعه", url: "https://ganjoor.net/roodaki" },
  { title: "شاهنامه", author: "فردوسی", century: 4, form: "مثنوی حماسی", kind: "مثنوی", url: "https://ganjoor.net/ferdousi" },
  { title: "گشتاسپ‌نامه", author: "دقیقی", century: 4, form: "مثنوی حماسی", kind: "مثنوی", url: "https://ganjoor.net/daghighi" },
  { title: "تاریخ بلعمی", author: "بلعمی", century: 4, form: "تاریخ‌نگاری", kind: "نثر", url: "https://ganjoor.net/balami" },
  { title: "دیوان عنصری", author: "عنصری", century: 4, form: "قصیده و غزل", kind: "دیوان", url: "https://ganjoor.net/onsori" },
  { title: "دوبیتی‌ها", author: "باباطاهر", century: 5, form: "دوبیتی", kind: "مجموعه", url: "https://ganjoor.net/babataher" },
  { title: "گرشاسپ‌نامه", author: "اسدی توسی", century: 5, form: "مثنوی حماسی", kind: "مثنوی", url: "https://ganjoor.net/asadi" },
  { title: "لغت فرس", author: "اسدی توسی", century: 5, form: "فرهنگ واژگان", kind: "نثر", url: "https://ganjoor.net/asadi" },
  { title: "تاریخ بیهقی", author: "ابوالفضل بیهقی", century: 5, form: "تاریخ‌نگاری ادبی", kind: "نثر", url: "https://ganjoor.net/beyhaghi" },
  { title: "ویس و رامین", author: "فخرالدین اسعد گرگانی", century: 5, form: "مثنوی عاشقانه", kind: "مثنوی", url: "https://ganjoor.net/asad" },
  { title: "قابوس‌نامه", author: "عنصرالمعالی", century: 5, form: "اندرزنامه", kind: "نثر", url: "https://ganjoor.net/keikavus" },
  { title: "مناجات‌نامه", author: "خواجه عبدالله انصاری", century: 5, form: "نثر آهنگین عرفانی", kind: "نثر", url: "https://ganjoor.net/abdullah" },
  { title: "دیوان ناصرخسرو", author: "ناصرخسرو", century: 5, form: "قصیده و قطعه", kind: "دیوان", url: "https://ganjoor.net/naserkhosro" },
  { title: "سفرنامه", author: "ناصرخسرو", century: 5, form: "سفرنامه", kind: "نثر", url: "https://ganjoor.net/naserkhosro" },
  { title: "روشنایی‌نامه", author: "ناصرخسرو", century: 5, form: "مثنوی حکمی", kind: "مثنوی", url: "https://ganjoor.net/naserkhosro" },
  { title: "سعادت‌نامه", author: "ناصرخسرو", century: 5, form: "مثنوی تعلیمی", kind: "مثنوی", url: "https://ganjoor.net/naserkhosro" },
  { title: "دیوان منوچهری", author: "منوچهری", century: 5, form: "قصیده و مسمط", kind: "دیوان", url: "https://ganjoor.net/manoochehri" },
  { title: "دیوان فرخی", author: "فرخی سیستانی", century: 5, form: "قصیده و غزل", kind: "دیوان", url: "https://ganjoor.net/farrokhi" },
  { title: "دیوان قطران", author: "قطران تبریزی", century: 5, form: "قصیده", kind: "دیوان", url: "https://ganjoor.net/ghatran" },
  { title: "حدیقةالحقیقه", author: "سنایی", century: 6, form: "مثنوی عرفانی", kind: "مثنوی", url: "https://ganjoor.net/sanaee" },
  { title: "سیرالعباد الی المعاد", author: "سنایی", century: 6, form: "مثنوی تمثیلی", kind: "مثنوی", url: "https://ganjoor.net/sanaee" },
  { title: "دیوان سنایی", author: "سنایی", century: 6, form: "قصیده و غزل", kind: "دیوان", url: "https://ganjoor.net/sanaee" },
  { title: "دیوان انوری", author: "انوری", century: 6, form: "قصیده، قطعه و غزل", kind: "دیوان", url: "https://ganjoor.net/anvari" },
  { title: "دیوان خاقانی", author: "خاقانی", century: 6, form: "قصیده و غزل", kind: "دیوان", url: "https://ganjoor.net/khaghani" },
  { title: "تحفةالعراقین", author: "خاقانی", century: 6, form: "سفرنامهٔ منظوم", kind: "مثنوی", url: "https://ganjoor.net/khaghani" },
  { title: "چهار مقاله", author: "نظامی عروضی", century: 6, form: "مقاله و حکایت", kind: "نثر", url: "https://ganjoor.net/aroozi" },
  { title: "کلیله و دمنه", author: "نصرالله منشی", century: 6, form: "نثر فنی و تمثیلی", kind: "نثر", url: "https://ganjoor.net/monshi" },
  { title: "کشف‌الاسرار", author: "میبدی", century: 6, form: "تفسیر و نثر عرفانی", kind: "نثر", url: "https://ganjoor.net/meybodi" },
  { title: "خمسه", author: "نظامی", century: 6, form: "پنج مثنوی", kind: "مجموعه", url: "https://ganjoor.net/nezami" },
  { title: "مخزن‌الاسرار", author: "نظامی", century: 6, form: "مثنوی تعلیمی", kind: "مثنوی", url: "https://ganjoor.net/nezami" },
  { title: "خسرو و شیرین", author: "نظامی", century: 6, form: "مثنوی عاشقانه", kind: "مثنوی", url: "https://ganjoor.net/nezami" },
  { title: "لیلی و مجنون", author: "نظامی", century: 6, form: "مثنوی عاشقانه", kind: "مثنوی", url: "https://ganjoor.net/nezami" },
  { title: "هفت پیکر", author: "نظامی", century: 6, form: "مثنوی روایی", kind: "مثنوی", url: "https://ganjoor.net/nezami" },
  { title: "اسکندرنامه", author: "نظامی", century: 6, form: "مثنوی روایی و حکمی", kind: "مثنوی", url: "https://ganjoor.net/nezami" },
  { title: "منطق‌الطیر", author: "عطار", century: 6, form: "مثنوی عرفانی", kind: "مثنوی", url: "https://ganjoor.net/attar" },
  { title: "الهی‌نامه", author: "عطار", century: 6, form: "مثنوی عرفانی", kind: "مثنوی", url: "https://ganjoor.net/attar" },
  { title: "مصیبت‌نامه", author: "عطار", century: 6, form: "مثنوی عرفانی", kind: "مثنوی", url: "https://ganjoor.net/attar" },
  { title: "اسرارنامه", author: "عطار", century: 6, form: "مثنوی عرفانی", kind: "مثنوی", url: "https://ganjoor.net/attar" },
  { title: "تذکرةالاولیا", author: "عطار", century: 6, form: "زندگی‌نامهٔ عارفان", kind: "تذکره", url: "https://ganjoor.net/attar" },
  { title: "دیوان عطار", author: "عطار", century: 6, form: "غزل و قصیده", kind: "دیوان", url: "https://ganjoor.net/attar" },
  { title: "رباعیات مهستی", author: "مهستی گنجوی", century: 6, form: "رباعی", kind: "رباعیات", url: "https://ganjoor.net/mahsati" },
  { title: "مثنوی معنوی", author: "مولانا", century: 7, form: "مثنوی عرفانی", kind: "مثنوی", url: "https://ganjoor.net/moulavi" },
  { title: "دیوان شمس", author: "مولانا", century: 7, form: "غزل و ترجیع", kind: "دیوان", url: "https://ganjoor.net/moulavi" },
  { title: "فیه ما فیه", author: "مولانا", century: 7, form: "مجالس و گفتار", kind: "نثر", url: "https://ganjoor.net/moulavi" },
  { title: "مجالس سبعه", author: "مولانا", century: 7, form: "خطابه و مجلس", kind: "نثر", url: "https://ganjoor.net/moulavi" },
  { title: "بوستان", author: "سعدی", century: 7, form: "مثنوی تعلیمی", kind: "مثنوی", url: "https://ganjoor.net/saadi" },
  { title: "گلستان", author: "سعدی", century: 7, form: "نثر مسجع و حکایت", kind: "نثر", url: "https://ganjoor.net/saadi" },
  { title: "غزلیات سعدی", author: "سعدی", century: 7, form: "غزل", kind: "دیوان", url: "https://ganjoor.net/saadi" },
  { title: "قصاید سعدی", author: "سعدی", century: 7, form: "قصیده", kind: "دیوان", url: "https://ganjoor.net/saadi" },
  { title: "دیوان امیرخسرو", author: "امیرخسرو دهلوی", century: 7, form: "غزل، قصیده و رباعی", kind: "دیوان", url: "https://ganjoor.net/khosro" },
  { title: "مطلع‌الانوار", author: "امیرخسرو دهلوی", century: 7, form: "مثنوی", kind: "مثنوی", url: "https://ganjoor.net/khosro" },
  { title: "هشت بهشت", author: "امیرخسرو دهلوی", century: 7, form: "مثنوی روایی", kind: "مثنوی", url: "https://ganjoor.net/khosro" },
  { title: "خسرو و شیرین", author: "امیرخسرو دهلوی", century: 7, form: "مثنوی عاشقانه", kind: "مثنوی", url: "https://ganjoor.net/khosro" },
  { title: "مجنون و لیلی", author: "امیرخسرو دهلوی", century: 7, form: "مثنوی عاشقانه", kind: "مثنوی", url: "https://ganjoor.net/khosro" },
  { title: "لمعات", author: "فخرالدین عراقی", century: 7, form: "نثر عرفانی", kind: "نثر", url: "https://ganjoor.net/eraghi" },
  { title: "عشاق‌نامه", author: "فخرالدین عراقی", century: 7, form: "مثنوی عرفانی", kind: "مثنوی", url: "https://ganjoor.net/eraghi" },
  { title: "دیوان عراقی", author: "فخرالدین عراقی", century: 7, form: "غزل، قصیده و رباعی", kind: "دیوان", url: "https://ganjoor.net/eraghi" },
  { title: "جام جم", author: "اوحدی مراغه‌ای", century: 8, form: "مثنوی تعلیمی", kind: "مثنوی", url: "https://ganjoor.net/ouhadi" },
  { title: "منطق‌العشاق", author: "اوحدی مراغه‌ای", century: 8, form: "مثنوی عرفانی", kind: "مثنوی", url: "https://ganjoor.net/ouhadi" },
  { title: "دیوان خواجو", author: "خواجوی کرمانی", century: 8, form: "غزل و قصیده", kind: "دیوان", url: "https://ganjoor.net/khajoo" },
  { title: "همای و همایون", author: "خواجوی کرمانی", century: 8, form: "مثنوی روایی", kind: "مثنوی", url: "https://ganjoor.net/khajoo" },
  { title: "گل و نوروز", author: "خواجوی کرمانی", century: 8, form: "مثنوی عاشقانه", kind: "مثنوی", url: "https://ganjoor.net/khajoo" },
  { title: "دیوان حافظ", author: "حافظ", century: 8, form: "غزل، قصیده و قطعه", kind: "دیوان", url: "https://ganjoor.net/hafez" },
  { title: "کلیات عبید", author: "عبید زاکانی", century: 8, form: "شعر و رساله", kind: "مجموعه", url: "https://ganjoor.net/obeyd" },
  { title: "اخلاق‌الاشراف", author: "عبید زاکانی", century: 8, form: "رسالهٔ طنز", kind: "نثر", url: "https://ganjoor.net/obeyd" },
  { title: "موش و گربه", author: "عبید زاکانی", century: 8, form: "منظومهٔ طنز", kind: "مثنوی", url: "https://ganjoor.net/obeyd" },
  { title: "دیوان جهان‌ملک خاتون", author: "جهان‌ملک خاتون", century: 8, form: "غزل، قصیده و رباعی", kind: "دیوان", url: "https://ganjoor.net/jahan" },
  { title: "دیوان سلمان", author: "سلمان ساوجی", century: 8, form: "قصیده و غزل", kind: "دیوان", url: "https://ganjoor.net/salman" },
  { title: "جمشید و خورشید", author: "سلمان ساوجی", century: 8, form: "مثنوی عاشقانه", kind: "مثنوی", url: "https://ganjoor.net/salman" },
  { title: "دیوان سیف فرغانی", author: "سیف فرغانی", century: 8, form: "غزل، قصیده و رباعی", kind: "دیوان", url: "https://ganjoor.net/seyf" },
  { title: "گلشن راز", author: "شیخ محمود شبستری", century: 8, form: "مثنوی عرفانی", kind: "مثنوی", url: "https://ganjoor.net/shabestari" },
  { title: "دیوان کمال خجندی", author: "کمال خجندی", century: 8, form: "غزل و قصیده", kind: "دیوان", url: "https://ganjoor.net/khojandi" },
  { title: "دیوان شاه نعمت‌الله", author: "شاه نعمت‌الله ولی", century: 8, form: "غزل و قصیده", kind: "دیوان", url: "https://ganjoor.net/shahnematollah" },
  { title: "هفت اورنگ", author: "جامی", century: 9, form: "هفت مثنوی", kind: "مجموعه", url: "https://ganjoor.net/jami" },
  { title: "بهارستان", author: "جامی", century: 9, form: "نثر و حکایت", kind: "نثر", url: "https://ganjoor.net/jami" },
  { title: "نفحات‌الانس", author: "جامی", century: 9, form: "تذکرهٔ عارفان", kind: "تذکره", url: "https://ganjoor.net/jami" },
  { title: "سه دیوان", author: "جامی", century: 9, form: "غزل، قصیده و قطعه", kind: "دیوان", url: "https://ganjoor.net/jami" },
  { title: "دیوان اهلی", author: "اهلی شیرازی", century: 10, form: "غزل و قصیده", kind: "دیوان", url: "https://ganjoor.net/ahli" },
  { title: "سحر حلال", author: "اهلی شیرازی", century: 10, form: "مثنوی مصنوع", kind: "مثنوی", url: "https://ganjoor.net/ahli" },
  { title: "دیوان وحشی", author: "وحشی بافقی", century: 10, form: "غزل، قصیده و ترکیب‌بند", kind: "دیوان", url: "https://ganjoor.net/vahshi" },
  { title: "فرهاد و شیرین", author: "وحشی بافقی", century: 10, form: "مثنوی عاشقانه", kind: "مثنوی", url: "https://ganjoor.net/vahshi" },
  { title: "دیوان محتشم", author: "محتشم کاشانی", century: 10, form: "غزل، قصیده و ترکیب‌بند", kind: "دیوان", url: "https://ganjoor.net/mohtasham" },
  { title: "دوازده‌بند", author: "محتشم کاشانی", century: 10, form: "ترکیب‌بند مرثیه", kind: "مجموعه", url: "https://ganjoor.net/mohtasham" },
  { title: "کشکول", author: "شیخ بهایی", century: 10, form: "جُنگ ادبی و علمی", kind: "نثر", url: "https://ganjoor.net/bahaee" },
  { title: "نان و حلوا", author: "شیخ بهایی", century: 10, form: "مثنوی عرفانی", kind: "مثنوی", url: "https://ganjoor.net/bahaee" },
  { title: "دیوان صائب", author: "صائب تبریزی", century: 11, form: "غزل و قصیده", kind: "دیوان", url: "https://ganjoor.net/saeb" },
  { title: "دیوان کلیم", author: "کلیم کاشانی", century: 11, form: "غزل و قصیده", kind: "دیوان", url: "https://ganjoor.net/kalim" },
  { title: "پادشاه‌نامه", author: "کلیم کاشانی", century: 11, form: "مثنوی تاریخی", kind: "مثنوی", url: "https://ganjoor.net/kalim" },
  { title: "کلیات بیدل", author: "بیدل دهلوی", century: 11, form: "شعر و نثر", kind: "مجموعه", url: "https://ganjoor.net/bidel" },
  { title: "چهار عنصر", author: "بیدل دهلوی", century: 11, form: "زندگی‌نامه و نثر ادبی", kind: "نثر", url: "https://ganjoor.net/bidel" },
  { title: "عرفان", author: "بیدل دهلوی", century: 11, form: "مثنوی فلسفی", kind: "مثنوی", url: "https://ganjoor.net/bidel" },
  { title: "دیوان هاتف", author: "هاتف اصفهانی", century: 12, form: "غزل، قصیده و رباعی", kind: "دیوان", url: "https://ganjoor.net/hatef" },
  { title: "ترجیع‌بند توحیدی", author: "هاتف اصفهانی", century: 12, form: "ترجیع‌بند", kind: "مجموعه", url: "https://ganjoor.net/hatef" },
  { title: "مجمع‌الفصحا", author: "رضاقلی خان هدایت", century: 13, form: "تذکرهٔ شاعران", kind: "تذکره", url: "https://ganjoor.net/rhedayat" },
  { title: "ریاض‌العارفین", author: "رضاقلی خان هدایت", century: 13, form: "تذکرهٔ عارفان", kind: "تذکره", url: "https://ganjoor.net/rhedayat" },
  { title: "دیوان فروغی", author: "فروغی بسطامی", century: 13, form: "غزل", kind: "دیوان", url: "https://ganjoor.net/forooghi" },
  { title: "دیوان قاآنی", author: "قاآنی", century: 13, form: "قصیده، غزل و قطعه", kind: "دیوان", url: "https://ganjoor.net/ghaani" },
  { title: "پریشان", author: "قاآنی", century: 13, form: "نثر به شیوهٔ گلستان", kind: "نثر", url: "https://ganjoor.net/ghaani" },
  { title: "دیوان یغما", author: "یغمای جندقی", century: 13, form: "غزل، قصیده و هزل", kind: "دیوان", url: "https://ganjoor.net/yaghma" },
  { title: "دیوان پروین", author: "پروین اعتصامی", century: 14, form: "قطعه، قصیده و مناظره", kind: "دیوان", url: "https://ganjoor.net/parvin" },
  { title: "دیوان بهار", author: "ملک‌الشعرا بهار", century: 14, form: "قصیده و شعر سیاسی", kind: "دیوان", url: "https://ganjoor.net/bahar" },
  { title: "پیام مشرق", author: "اقبال لاهوری", century: 14, form: "شعر فلسفی فارسی", kind: "مجموعه", url: "https://ganjoor.net/iqbal" },
  { title: "دیوان مسعود سعد سلمان", author: "مسعود سعد سلمان", century: 5, form: "قصیده، قطعه و غزل", kind: "دیوان", url: "https://ganjoor.net/masood" },
  { title: "حبسیات", author: "مسعود سعد سلمان", century: 5, form: "قصاید زندان", kind: "مجموعه", url: "https://ganjoor.net/masood" },
  { title: "تمهیدات", author: "عین‌القضات همدانی", century: 6, form: "نثر عرفانی و فلسفی", kind: "نثر", url: "https://ganjoor.net/eynolghozat" },
  { title: "لوایح", author: "عین‌القضات همدانی", century: 6, form: "رسالهٔ عرفانی", kind: "نثر", url: "https://ganjoor.net/eynolghozat" },
  { title: "نامه‌ها", author: "عین‌القضات همدانی", century: 6, form: "مکاتبات عرفانی", kind: "نثر", url: "https://ganjoor.net/eynolghozat" },
  { title: "رباعیات باباافضل", author: "باباافضل کاشانی", century: 6, form: "رباعی حکمی", kind: "رباعیات", url: "https://ganjoor.net/babaafzal/robba" },
  { title: "رساله‌های حکمی", author: "باباافضل کاشانی", century: 6, form: "نثر فلسفی فارسی", kind: "نثر", url: "https://ganjoor.net/babaafzal" },
  { title: "مختارنامه", author: "عطار نیشابوری", century: 6, form: "مجموعهٔ رباعیات", kind: "رباعیات", url: "https://ganjoor.net/attar" },
  { title: "دیوان همام تبریزی", author: "همام تبریزی", century: 7, form: "غزل، قصیده و مثنوی", kind: "دیوان", url: "https://ganjoor.net/homam" },
  { title: "دیوان ابن یمین", author: "ابن یمین فریومدی", century: 8, form: "قطعه، قصیده و غزل", kind: "دیوان", url: "https://ganjoor.net/ebneyamin" },
  { title: "دیوان قاسم انوار", author: "قاسم انوار", century: 8, form: "غزل، مثنوی و قطعه", kind: "دیوان", url: "https://ganjoor.net/ghasem" },
  { title: "صد پند", author: "عبید زاکانی", century: 8, form: "رسالهٔ طنز و اندرز", kind: "نثر", url: "https://ganjoor.net/obeyd" },
  { title: "رسالهٔ دلگشا", author: "عبید زاکانی", century: 8, form: "حکایت و طنز", kind: "نثر", url: "https://ganjoor.net/obeyd" },
  { title: "روضةالانوار", author: "خواجوی کرمانی", century: 8, form: "مثنوی عرفانی", kind: "مثنوی", url: "https://ganjoor.net/khajoo" },
  { title: "کمال‌نامه", author: "خواجوی کرمانی", century: 8, form: "مثنوی عرفانی", kind: "مثنوی", url: "https://ganjoor.net/khajoo" },
  { title: "یوسف و زلیخا", author: "جامی", century: 9, form: "مثنوی عاشقانه و عرفانی", kind: "مثنوی", url: "https://ganjoor.net/jami" },
  { title: "سلامان و ابسال", author: "جامی", century: 9, form: "مثنوی تمثیلی", kind: "مثنوی", url: "https://ganjoor.net/jami" },
  { title: "دیوان عرفی شیرازی", author: "عرفی شیرازی", century: 10, form: "قصیده و غزل", kind: "دیوان", url: "https://ganjoor.net/orfi" },
  { title: "دیوان نظیری نیشابوری", author: "نظیری نیشابوری", century: 10, form: "غزل و قصیده", kind: "دیوان", url: "https://ganjoor.net/naziri" },
  { title: "دیوان فیض کاشانی", author: "فیض کاشانی", century: 11, form: "غزل، قصیده و رباعی", kind: "دیوان", url: "https://ganjoor.net/feyz" },
  { title: "طور معرفت", author: "بیدل دهلوی", century: 11, form: "مثنوی عرفانی و فلسفی", kind: "مثنوی", url: "https://ganjoor.net/bidel" },
  { title: "طلسم حیرت", author: "بیدل دهلوی", century: 11, form: "مثنوی", kind: "مثنوی", url: "https://ganjoor.net/bidel" },
  { title: "دیوان حزین لاهیجی", author: "حزین لاهیجی", century: 12, form: "غزل و قصیده", kind: "دیوان", url: "https://ganjoor.net/hazin" },
  { title: "تذکرةالمعاصرین", author: "حزین لاهیجی", century: 12, form: "تذکرهٔ شاعران", kind: "تذکره", url: "https://ganjoor.net/hazin" },
  { title: "آتشکدهٔ آذر", author: "آذر بیگدلی", century: 12, form: "تذکرهٔ شاعران", kind: "تذکره", url: "https://ganjoor.net/azar" },
  { title: "دیوان آذر بیگدلی", author: "آذر بیگدلی", century: 12, form: "غزل و قصیده", kind: "دیوان", url: "https://ganjoor.net/azar" },
];

export const workCatalog: WorkRecord[] = workSeed.map((work, index) => ({ ...work, id: index + 1 }));

export const literaryMovements: LiteraryMovement[] = [
  {
    title: "آغاز شعر دری",
    centuries: "سده‌های ۳ تا ۵",
    description: "تثبیت فارسی دری در دربارهای شرقی، شکل‌گیری قصیده و نخستین منظومه‌های حماسی و روایی.",
    features: ["زبان نسبتاً ساده", "پیوند با دربار", "حماسه و مدح"],
    figures: ["رودکی", "دقیقی", "فردوسی", "عنصری"],
    sourceUrl: "https://www.iranicaonline.org/articles/iran-viii2-classical-persian-literature/",
  },
  {
    title: "سبک خراسانی",
    centuries: "سده‌های ۴ تا ۶",
    description: "قصیدهٔ استوار، تصویر طبیعت، واژگان حسی و روایت‌های حماسی در خراسان و حوزه‌های سامانی و غزنوی.",
    features: ["قصیده", "طبیعت‌گرایی", "ترکیب‌های روشن"],
    figures: ["فرخی", "منوچهری", "ناصرخسرو", "انوری"],
    sourceUrl: "https://www.iranicaonline.org/articles/iran-viii2-classical-persian-literature/",
  },
  {
    title: "سنت عراقی و عرفانی",
    centuries: "سده‌های ۶ تا ۹",
    description: "گسترش غزل و مثنوی عرفانی، زبان عاشقانه و شبکهٔ خانقاه‌ها و مراکز فرهنگی از خراسان تا فارس و آناتولی.",
    features: ["غزل", "عرفان", "ایهام و تمثیل"],
    figures: ["عطار", "مولانا", "سعدی", "حافظ"],
    sourceUrl: "https://www.iranicaonline.org/articles/iran-viii2-classical-persian-literature/",
  },
  {
    title: "سبک هندی یا اصفهانی",
    centuries: "سده‌های ۱۰ تا ۱۲",
    description: "مضمون‌آفرینی، تصویرهای دور و فشرده و رفت‌وآمد گستردهٔ شاعران میان ایران و دربارهای فارسی‌زبان هند.",
    features: ["مضمون تازه", "تمثیل روزمره", "خیال فشرده"],
    figures: ["صائب", "کلیم", "بیدل", "غنی کشمیری"],
    sourceUrl: "https://www.iranicaonline.org/articles/iran-viii2-classical-persian-literature/",
  },
  {
    title: "بازگشت و گذار به معاصر",
    centuries: "سده‌های ۱۲ تا ۱۴",
    description: "بازخوانی سبک‌های خراسانی و عراقی و سپس ورود موضوعات اجتماعی، سیاسی و آموزشی به شعر دورهٔ مشروطه و پس از آن.",
    features: ["بازگشت به قصیده", "زبان اجتماعی", "رسانه و سیاست"],
    figures: ["هاتف", "قاآنی", "بهار", "پروین"],
    sourceUrl: "https://ganjoor.net/",
  },
];

export const librarySources: LibrarySource[] = [
  {
    id: 1,
    title: "گنجور؛ گنجینهٔ شعر و ادب فارسی",
    author: "پروژهٔ گنجور",
    period: "از سدهٔ سوم تا معاصر",
    type: "پیکرهٔ متن",
    format: "متن، فراداده و نمایهٔ شاعر/اثر",
    access: "دسترسی عمومی",
    coverage: "صدها شاعر و نویسنده با دسته‌بندی سده‌ای",
    description: "پیکره‌ای برخط برای خواندن، جست‌وجو و پیمایش آثار فارسی با صفحه‌های مستقل برای پدیدآورندگان و آثار.",
    url: "https://ganjoor.net/",
    color: "gold",
  },
  {
    id: 2,
    title: "رابط برنامه‌نویسی گنجور",
    author: "Ganjoor API",
    period: "زیرساخت معاصر",
    type: "زیرساخت داده",
    format: "REST API و مستندات فنی",
    access: "مستندات عمومی",
    coverage: "شاعران، آثار، ابیات، جست‌وجو و فراداده",
    description: "مستندات رسمی برای دسترسی ماشینی به ساختار داده‌های گنجور و ساخت ابزارهای پژوهشی پیرامون آن.",
    url: "https://api.ganjoor.net/index.html",
    color: "cyan",
  },
  {
    id: 3,
    title: "ادبیات کلاسیک فارسی",
    author: "Encyclopaedia Iranica",
    period: "دورهٔ کلاسیک",
    type: "دانش‌نامه",
    format: "مدخل مرجع برخط",
    access: "مطالعهٔ عمومی",
    coverage: "تحول ژانرها، دوره‌ها و چهره‌های اصلی",
    description: "مروری دانش‌نامه‌ای بر شکل‌گیری و تحول قصیده، غزل، مثنوی و سنت‌های سبکی در ادبیات کلاسیک فارسی.",
    url: "https://www.iranicaonline.org/articles/iran-viii2-classical-persian-literature/",
    color: "wine",
  },
  {
    id: 4,
    title: "Wikidata؛ دانش‌نگار آزاد",
    author: "جامعهٔ ویکی‌داده",
    period: "دادهٔ زنده",
    type: "زیرساخت داده",
    format: "دانش‌نگار و SPARQL",
    access: "CC0",
    coverage: "شناسه‌ها، تاریخ‌ها، مکان‌ها و پیوندهای بین‌زبانی",
    description: "پایگاه دانش آزاد برای هم‌ارزی نام‌ها، شناسه‌های یکتا و اتصال داده‌های ادبی به منابع چندزبانه.",
    url: "https://www.wikidata.org/wiki/Wikidata:Main_Page",
    color: "cyan",
  },
  {
    id: 5,
    title: "Chronological Persian Poetry Dataset",
    author: "Ali Ghasemi و همکاران",
    period: "شعر فارسی به‌ترتیب تاریخی",
    type: "دادهٔ پژوهشی",
    format: "مجموعه‌داده و کد",
    access: "CC BY-SA 4.0",
    coverage: "داده‌های استخراج‌شده از گنجور با محور زمان",
    description: "مجموعه‌داده‌ای باز برای مطالعهٔ رایانشی شعر فارسی در امتداد تاریخی، همراه با کد و توضیحات بازتولیدپذیری.",
    url: "https://github.com/aghasemi/ChronologicalPersianPoetryDataset",
    color: "gold",
  },
  {
    id: 6,
    title: "A standard literary Persian corpus",
    author: "Language Resources and Evaluation",
    period: "پژوهش معاصر",
    type: "دادهٔ پژوهشی",
    format: "مقاله و شرح پیکره",
    access: "صفحهٔ مقاله",
    coverage: "شاعر، سده، سبک و قالب‌های غزل، قصیده و مثنوی",
    description: "شرح یک پیکرهٔ ادبی فارسی با فرادادهٔ شاعر و سده و برچسب‌های دوره‌ای و سبکی برای پژوهش محاسباتی.",
    url: "https://link.springer.com/article/10.1007/s10579-023-09689-6",
    color: "wine",
  },
  {
    id: 7,
    title: "شاهنامهٔ فردوسی",
    author: "فردوسی توسی / گنجور",
    period: "سدهٔ چهارم و پنجم",
    type: "مجموعهٔ شاعر",
    format: "متن ساختاریافته برخط",
    access: "مطالعهٔ عمومی",
    coverage: "شاهنامه و فرادادهٔ بخش‌ها",
    description: "دسترسی ساختاریافته به شاهنامه و صفحهٔ زندگی‌نامه و آمار قالب‌های شعری فردوسی.",
    url: "https://ganjoor.net/ferdousi",
    color: "wine",
  },
  {
    id: 8,
    title: "آثار مولانا",
    author: "مولانا جلال‌الدین بلخی / گنجور",
    period: "سدهٔ هفتم",
    type: "مجموعهٔ شاعر",
    format: "متن ساختاریافته برخط",
    access: "مطالعهٔ عمومی",
    coverage: "مثنوی، دیوان شمس، رباعیات و فیه ما فیه",
    description: "صفحهٔ جامع آثار منظوم و منثور مولانا با نمایهٔ کتاب‌ها و دسترسی مستقیم به بخش‌های متن.",
    url: "https://ganjoor.net/moulavi",
    color: "gold",
  },
  {
    id: 9,
    title: "کلیات سعدی",
    author: "سعدی شیرازی / گنجور",
    period: "سدهٔ هفتم",
    type: "مجموعهٔ شاعر",
    format: "متن ساختاریافته برخط",
    access: "مطالعهٔ عمومی",
    coverage: "بوستان، گلستان، غزلیات، قصاید و رسائل",
    description: "مجموعهٔ برخط آثار سعدی، از دو اثر تعلیمی اصلی تا غزلیات و نوشته‌های کوتاه‌تر.",
    url: "https://ganjoor.net/saadi",
    color: "cyan",
  },
  {
    id: 10,
    title: "دیوان حافظ",
    author: "حافظ شیرازی / گنجور",
    period: "سدهٔ هشتم",
    type: "مجموعهٔ شاعر",
    format: "متن ساختاریافته برخط",
    access: "مطالعهٔ عمومی",
    coverage: "غزلیات، قصاید، قطعات، رباعیات و مثنوی‌ها",
    description: "صفحهٔ برخط دیوان حافظ همراه با دسته‌بندی قالب‌ها و فرادادهٔ زندگی‌نامه‌ای.",
    url: "https://ganjoor.net/hafez",
    color: "gold",
  },
  {
    id: 11,
    title: "آثار عطار نیشابوری",
    author: "عطار نیشابوری / گنجور",
    period: "سدهٔ ششم و هفتم",
    type: "مجموعهٔ شاعر",
    format: "متن ساختاریافته برخط",
    access: "مطالعهٔ عمومی",
    coverage: "منطق‌الطیر، الهی‌نامه، مصیبت‌نامه، دیوان و تذکرةالاولیا",
    description: "یکی از گسترده‌ترین مجموعه‌های متنی عرفان فارسی با آثار منظوم و منثور منسوب به عطار.",
    url: "https://ganjoor.net/attar",
    color: "wine",
  },
  {
    id: 12,
    title: "خمسهٔ نظامی",
    author: "نظامی گنجوی / گنجور",
    period: "سدهٔ ششم",
    type: "مجموعهٔ شاعر",
    format: "متن ساختاریافته برخط",
    access: "مطالعهٔ عمومی",
    coverage: "پنج مثنوی اصلی و دیوان",
    description: "منبع برخط منظومه‌های روایی نظامی و نقطهٔ ورود به پنج گنج و دیوان او.",
    url: "https://ganjoor.net/nezami",
    color: "cyan",
  },
  {
    id: 13,
    title: "GanjoorService؛ کد منبع خدمت داده",
    author: "پروژهٔ گنجور",
    period: "زیرساخت معاصر",
    type: "زیرساخت داده",
    format: "کد منبع، مدل داده و API",
    access: "GPL-3.0",
    coverage: "خدمت وب، پایگاه داده و مسیرهای دسترسی به متن و فراداده",
    description: "مخزن رسمی بخش پشتی گنجور برای بررسی ساختار فنی، مدل‌های داده و روش ارائهٔ ماشینی محتوای ادبی.",
    url: "https://github.com/ganjoor/GanjoorService",
    color: "cyan",
  },
  {
    id: 14,
    title: "دیوان مسعود سعد سلمان",
    author: "مسعود سعد سلمان / گنجور",
    period: "سدهٔ پنجم و ششم",
    type: "مجموعهٔ شاعر",
    format: "متن ساختاریافته برخط",
    access: "مطالعهٔ عمومی",
    coverage: "قصاید، حبسیات، قطعات، غزلیات و رباعیات",
    description: "پیکرهٔ برخط یکی از مهم‌ترین دیوان‌های دورهٔ غزنوی با بیش از پانزده هزار بیت و نمونه‌های شاخص حبسیه.",
    url: "https://ganjoor.net/masood",
    color: "wine",
  },
  {
    id: 15,
    title: "آثار عین‌القضات همدانی",
    author: "عین‌القضات همدانی / گنجور",
    period: "سدهٔ ششم",
    type: "مجموعهٔ شاعر",
    format: "نثر عرفانی و فرادادهٔ برخط",
    access: "مطالعهٔ عمومی",
    coverage: "تمهیدات، لوایح، نامه‌ها و نوشته‌های منسوب",
    description: "نقطهٔ ورود به نوشته‌های فارسی عین‌القضات و شبکهٔ مفاهیم عرفانی و فلسفی در نثر سدهٔ ششم.",
    url: "https://ganjoor.net/eynolghozat",
    color: "gold",
  },
  {
    id: 16,
    title: "آثار فیض کاشانی",
    author: "فیض کاشانی / گنجور",
    period: "سدهٔ یازدهم",
    type: "مجموعهٔ شاعر",
    format: "متن منظوم و نمایهٔ آثار",
    access: "مطالعهٔ عمومی",
    coverage: "غزل، قصیده، رباعی و منظومه‌های عرفانی",
    description: "مجموعهٔ برخط شعر فیض برای مطالعهٔ پیوند ادبیات، عرفان و حکمت در فرهنگ دورهٔ صفوی.",
    url: "https://ganjoor.net/feyz",
    color: "gold",
  },
];

export const literaryCenters = {
  "شیراز": {
    note: "یکی از پایدارترین کانون‌های غزل، نثر تعلیمی و فرهنگ درباری در سده‌های هفتم تا دهم.",
    names: ["سعدی", "حافظ", "جهان‌ملک خاتون", "خواجوی کرمانی", "اهلی"],
    period: "سده‌های ۷ تا ۱۰",
    tradition: "غزل و نثر تعلیمی",
    sourceUrl: "https://ganjoor.net/",
    left: "48%", top: "76%",
  },
  "خراسان": {
    note: "حوزه‌ای گسترده و خاستگاه شعر دری، حماسه، قصیدهٔ درباری و بخش مهمی از ادبیات عرفانی.",
    names: ["فردوسی", "عنصری", "فرخی", "منوچهری", "ناصرخسرو"],
    period: "سده‌های ۳ تا ۷",
    tradition: "سبک خراسانی و حماسه",
    sourceUrl: "https://www.iranicaonline.org/articles/iran-viii2-classical-persian-literature/",
    left: "72%", top: "27%",
  },
  "نیشابور": {
    note: "کانونی مهم در خراسان برای رباعی، تصوف و روایت عرفانی.",
    names: ["خیام", "عطار", "نظیری"],
    period: "سده‌های ۵ تا ۱۰",
    tradition: "رباعی و عرفان",
    sourceUrl: "https://ganjoor.net/",
    left: "67%", top: "38%",
  },
  "توس": {
    note: "کانون پیوندخورده با سنت حماسی فارسی و میراث شاهنامه.",
    names: ["فردوسی", "اسدی توسی"],
    period: "سده‌های ۴ و ۵",
    tradition: "حماسه و فرهنگ‌نامه",
    sourceUrl: "https://ganjoor.net/ferdousi",
    left: "73%", top: "34%",
  },
  "تبریز": {
    note: "پیوندگاه سنت‌های آذربایجان، ایران مرکزی و شبکه‌های ادبی آناتولی و قفقاز.",
    names: ["قطران", "همام", "صائب", "پروین", "شهریار"],
    period: "سده‌های ۵ تا ۱۴",
    tradition: "قصیده، غزل و شعر معاصر",
    sourceUrl: "https://ganjoor.net/",
    left: "19%", top: "20%",
  },
  "اصفهان": {
    note: "مرکز مهم محافل ادبی صفوی و یکی از کانون‌های اصلی مضمون‌آفرینی در سبک هندی.",
    names: ["صائب", "کلیم", "محتشم", "هاتف"],
    period: "سده‌های ۱۰ تا ۱۲",
    tradition: "سبک هندی و بازگشت ادبی",
    sourceUrl: "https://ganjoor.net/saeb",
    left: "42%", top: "56%",
  },
  "گنجه": {
    note: "کانون برجستهٔ منظومه‌سرایی روایی در قفقاز و زادبوم سنت خمسه‌سرایی نظامی.",
    names: ["نظامی", "مهستی"],
    period: "سدهٔ ۶",
    tradition: "مثنوی روایی و رباعی",
    sourceUrl: "https://ganjoor.net/nezami",
    left: "24%", top: "30%",
  },
  "بلخ": {
    note: "از مراکز کهن فرهنگ فارسی و نقطهٔ آغاز زندگی چند چهرهٔ اثرگذار عرفان و شعر تعلیمی.",
    names: ["مولانا", "شهید بلخی", "ناصرخسرو"],
    period: "سده‌های ۴ تا ۷",
    tradition: "شعر دری و عرفان",
    sourceUrl: "https://ganjoor.net/moulavi",
    left: "83%", top: "23%",
  },
  "هرات": {
    note: "مرکز درخشان فرهنگ تیموری و محل تلاقی شعر، نگارگری، عرفان و تذکره‌نویسی.",
    names: ["جامی", "امیرعلیشیر نوایی", "فصیحی هروی"],
    period: "سده‌های ۹ تا ۱۱",
    tradition: "غزل، مثنوی و تذکره",
    sourceUrl: "https://ganjoor.net/jami",
    left: "78%", top: "46%",
  },
  "دهلی": {
    note: "یکی از مهم‌ترین مراکز فرامرزی فارسی در شبه‌قاره و بستر رشد شعر فارسی هند.",
    names: ["امیرخسرو", "بیدل", "غالب"],
    period: "سده‌های ۷ تا ۱۳",
    tradition: "غزل و سبک هندی",
    sourceUrl: "https://ganjoor.net/bidel",
    left: "89%", top: "69%",
  },
  "غزنه": {
    note: "دربار غزنوی یکی از مهم‌ترین بسترهای تثبیت قصیدهٔ فارسی و پیوند شعر با تاریخ، موسیقی و فرهنگ درباری بود.",
    names: ["عنصری", "فرخی", "منوچهری", "سنایی", "مسعود سعد"],
    period: "سده‌های ۴ تا ۶",
    tradition: "قصیدهٔ درباری و شعر تعلیمی",
    sourceUrl: "https://ganjoor.net/farrokhi",
    left: "86%", top: "34%",
  },
  "همدان": {
    note: "کانونی در غرب ایران برای دوبیتی، نثر عرفانی و شبکه‌های صوفیانه در چند دورهٔ تاریخی.",
    names: ["باباطاهر", "عین‌القضات", "فخرالدین عراقی"],
    period: "سده‌های ۵ تا ۷",
    tradition: "دوبیتی و نثر عرفانی",
    sourceUrl: "https://ganjoor.net/eynolghozat",
    left: "31%", top: "48%",
  },
  "کاشان": {
    note: "از مراکز پیوستهٔ فلسفه‌نویسی، مرثیه، غزل صفوی و مضمون‌آفرینی در مسیر ایران و هند.",
    names: ["باباافضل", "محتشم", "کلیم", "فیض"],
    period: "سده‌های ۶ تا ۱۱",
    tradition: "حکمت، مرثیه و غزل",
    sourceUrl: "https://ganjoor.net/feyz",
    left: "47%", top: "62%",
  },
  "بخارا و سمرقند": {
    note: "قلمرو سامانی و یکی از خاستگاه‌های نخستین شعر فارسی دری، فرهنگ دیوانی و شبکهٔ شاعران آغازین.",
    names: ["رودکی", "شهید بلخی", "دقیقی", "سوزنی"],
    period: "سده‌های ۳ تا ۶",
    tradition: "آغاز شعر دری و قصیده",
    sourceUrl: "https://ganjoor.net/roodaki",
    left: "69%", top: "12%",
  },
  "لاهور": {
    note: "یکی از گذرگاه‌های مهم فارسی در شبه‌قاره و محل فعالیت شاعران درباری، مهاجر و متفکر از دورهٔ غزنوی تا روزگار معاصر.",
    names: ["مسعود سعد", "عرفی", "اقبال"],
    period: "سده‌های ۵ تا ۱۴",
    tradition: "حبسیه، سبک هندی و شعر فلسفی",
    sourceUrl: "https://ganjoor.net/masood",
    left: "94%", top: "54%",
  },
} as const;

export const openReferences = [
  { title: "گنجور", detail: "فهرست سده‌ای و صفحه‌های آثار", url: "https://ganjoor.net/" },
  { title: "خدمت دادهٔ گنجور", detail: "کد منبع و مدل‌های API با مجوز GPL-3.0", url: "https://github.com/ganjoor/GanjoorService" },
  { title: "مستندات API گنجور", detail: "دسترسی ماشینی به شاعر، اثر و فراداده", url: "https://api.ganjoor.net/index.html" },
  { title: "دانشنامهٔ ایرانیکا", detail: "مرور تاریخ ادبیات کلاسیک", url: "https://www.iranicaonline.org/articles/iran-viii2-classical-persian-literature/" },
  { title: "ویکی‌داده", detail: "شناسه‌ها و دانش‌نگار آزاد CC0", url: "https://www.wikidata.org/wiki/Wikidata:Main_Page" },
  { title: "مجموعه‌دادهٔ تاریخی شعر فارسی", detail: "داده و کد با مجوز باز", url: "https://github.com/aghasemi/ChronologicalPersianPoetryDataset" },
  { title: "پیکرهٔ استاندارد ادبی فارسی", detail: "مقالهٔ روش و فرادادهٔ پیکره", url: "https://link.springer.com/article/10.1007/s10579-023-09689-6" },
];
